config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index', to: 'welcome#index', as: :welcome_index

  devise_for :cashiers, path: 'cashiers'
  
  devise_for :admins, path: 'admins'
  
  resources :products
  get '/report', to: 'products#report', as: :products_reports
  
  
  resources :cashiers, except: :create
  post 'create_cashier' => 'cashiers#create', as: :create_cashier
  
  resources :orders
  post 'orders/summary', to: 'orders#summary', as: :orders_summary
  get 'cashierreport/:id', to: 'orders#cashierreport', as: :cashierreport
  get 'orders/:id/refund/', to: 'orders#refund', as: :orders_refund
  post 'orders/:id', to: 'orders#update', as: :update_order
  
  resources :cashiers_admin, :controller => 'cashiers'
  

  root :to => 'welcome#index'
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :cashier
    has_many :order_lines
    has_many :products
    
    accepts_nested_attributes_for :order_lines
    accepts_nested_attributes_for :products
    
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_cashier!
    
    def new
        @order = Order.new
    end
    
    def index
        @orders = Order.all
    end
    
    def refund
        @order = Order.find(params[:id])
    end
    
    def update
        @order = Order.find(params[:id])
        @order.update(order_params)
        total = 0
        @order.order_lines.each do |p|
            subtotal = p.product.price*p.quantity
            total = subtotal + total
        end
        @order.total_price = total
        @order.save
        redirect_to @order
    end
    
    def edit
        @order = Order.find(params[:id])
        if @order.cashier != current_cashier
            redirect_to orders_path
        end
    end
    
    def summary
        @order = Order.new(order_params)
        total = 0
        @order.order_lines.each do |p|
            subtotal = p.product.price*p.quantity
            total = subtotal + total
        end
        @order.total_price = total
    end
    
    def cashierreport
 		@cashier = current_cashier
 		#@order.order_lines.each do |p|
 		#    @product = p.product.where(cashier: @cashier)
 		#end
		#@lines = @Cashier.orderswhere("created_at >= ? AND cashier_id = ?", Time.zone.now.beginning_of_day, @Cashier.id)
		#@all_orders = Order.all.where(["created_at >= ? and cashier_id = ?", Time.zone.now.beginning_of_day, Cashier: @Cashier.id])
		#@all_lines = Array.new()
# 		@all = OrderLine.where(cashier: current_cashiers)
		#@all_orders.each do |order|
		# 	@all.each do |line|
		# 		if line.order_id == order.id
		# 			@all_lines.push(line)
		# 		end
		# 	end
		#end
		@order = Order.where(cashier_id:current_cashier)
		@ord = @order.each.order_lines
		raise @ord.inspect
# 		render plain: @all_lines.inspect
	end
	
    def report
        @orders = Order.all
        # @orders = Order.new(order_params)
        # quantity = 0
        # temp_product_id = 0
        # @order.order_lines.each do |p|
        #     if p.order.id == 0
        #         temp_product_id = p.product_id
        #         quantity += p.quantity
        #     else 
        #         if p.product.id == temp_product_id
        #             quantity += p.quantity
        #         end
        #     end
        # end
        # redirect_to orders_path
    end
    
    def create
        @order = Order.new(order_params)
        @order.cashier = current_cashier
        @order.save
        #raise order_params.inspect
        redirect_to @order
    end
    
    def show
        @order = Order.find(params[:id])
        if !@order.present?
            redirect_to order_path
        end
    end
   
    
    def destroy
        @order = Order.find(params[:id])
        @order.destroy
        
        redirect_to orders_path
    end
    
   
    private
        def order_params
            params.require(:order).permit!
        end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order_line_fields.html.erb
<br>
<div class="nested-fields">
    <table class="table table-striped">
    <tr>
        <td><%= f.association :product, collection: Product.where(status: true), :class => 'browser-default' %></td>
        <td><%= f.input :quantity, input_html: {value: f.object.quantity || '1'}, class: "form-control" %> </td>
        <td><%= link_to_remove_association "Remove Product", f, class: "btn btn-danger" %></td>
    </tr>
</div>

app/views/orders/_order_line_refund.html.erb
<br>

<div class="nested-fields">
    <table class="table table-striped">
    <tr>
        <td>  <%= f.association :product, size: 40, collection: Product.where(status:true) %> </td> 
        <td>  <%= f.input :quantity, input_html: {value: f.object.quantity || '1'}, class: "form-control" %> </td>
    </tr>
</div>

app/views/orders/_orderform.html.erb
<%= simple_form_for @order, url: orders_summary_path do |f| %>
    <p>
            <%= link_to_add_association "Add Product", f, :order_lines, "data-association-insertion-method": "append", 
                    "data-association-insertion-node": "#order_lines", class: "btn btn-primary" %>
            <div id="order_lines">
                <%= f.simple_fields_for :order_lines do |order_line| %>
                    <%= render 'order_line_fields', f: order_line %>
                <% end %>
            </div>
    </p>


<%= f.submit "Create Order", class: "btn btn-primary" %>
<%= link_to "Cancel", orders_path, class: "btn btn-info" %>

<% end %>

</div>
</div>

app/views/orders/edit.html.erb
<fieldset>
<br>

<%= simple_form_for @order, url: orders_summary_path do |f| %>
    <p>
        <%= link_to_add_association "Add Product", f, :order_lines, "data-association-insertion-method": "append", 
                    "data-association-insertion-node": "#order_lines", class: "btn btn-primary" %>
            <div id="order_lines">
                <%= f.simple_fields_for :order_lines do |order_line| %>
                    <%= render 'order_line_fields', f: order_line %>
                <% end %>
            </div>
    </p>


<%= f.submit "Create Order", class: "btn btn-primary" %>
<%= link_to "Cancel", orders_path, class: "btn btn-info" %>

<% end %>

</fieldset>

app/views/orders/index.html.erb
<div class="card">
  <div class="card-block">
<br>
<h2>Orders</h2>
<br>
<%= link_to "New Order", new_order_path, class: "btn btn-info" %>
<table class="table table-striped">
   <thead>
        <tr>
             <th>Order #</th>
             <th>Cashier</th>
             <th>Total</th>
             <th>Cash</th>
             <th>Order</th>
        </tr>
   </thead>
   <tbody>
        <% @orders.each do |p| %>
            <tr>
                <td><%= p.id %></td>
                <td><%= p.cashier.name %></td>
                <td><%= p.total_price %></td>
                <td><%= if p.cash then p.cash else "NA" end %></td>
                <td><%= link_to "Show", order_path(p), class: "btn btn-info" %></td>
            </tr>
        <% end %>
   </tbody>
</table>
</div>
</div>

app/views/orders/new.html.erb
<br>

<h1>New Order</h1>
<%= render 'orderform' %>

app/views/orders/refund.html.erb
<div class="card">
  <div class="card-block">
<br>

<h1>Refund Order</h1>
<%= simple_form_for @order, url: update_order_path do |f| %>

<%= f.submit "Amend Order", class: "btn btn-danger" %>
<%= link_to "Cancel", orders_path, class: "btn btn-info" %>

    <p>
        <div id="order_lines">
            <%= f.simple_fields_for :order_lines do |order_line| %>
                <%= render 'order_line_refund', f: order_line %>
            <% end %>
        </div>
    </p>
    

<% end %>

</div>
</div>

app/views/orders/show.erb
<div class="card">
  <div class="card-block">
<br>

<h1>Order Summary</h1>
<table class="table table-striped">
    <tr>
         <th>Product</th> <th>Quantity</th> <th>Subtotal</th>
    </tr>
      <% @order.order_lines.each do |p| %>
        <tr>
            <td><%= p.product.name %> @ <%= p.product.price %></td>
            <td><%= p.quantity %></td>
            <td><%= p.product.price*p.quantity %></td>
        </tr>
    <% end %>
   
</table>

<h3>
    Total: <%= @order.total_price %>
</h3>

<h3>
    Cash: <%= @order.cash %>
</h3>

<h3>
    Change: <%= @order.cash - @order.total_price %>
</h3>

<p>
    <%= link_to "Back", orders_path, class: "btn btn-info" %>
    <%= link_to 'Print Summary', "#", class: "btn btn-primary", onclick: 'window.print();return false;'%>
    <%= link_to 'Refund', orders_refund_path(@order), class: "btn btn-warning" %>
</p>

</div>
</div>

app/views/orders/summary.html.erb
<div class="card">
  <div class="card-block">
<br>
<h1>Confirm Order</h1>
<table class="table table-striped">
    <tr>
         <th>Product</th> 
         <th>Quantity</th> 
         <th>Subtotal</th>
    </tr>
    <% @order.order_lines.each do |p| %>
        <tr>
            <td><%= p.product.name %> @ <%= p.product.price %></td>
            <td><%= p.quantity %></td>
            <td><%= p.product.price*p.quantity %></td>
        </tr>
    <% end %>
   
</table>

<h3>
    Total: <%= @order.total_price %>
</h3>

<p>
     <%= simple_form_for @order do |f| %>
         <p>
            <%= f.input :cash %>
        </p>
        <%= f.submit "Create Order", class: "btn btn-primary" %>
        <%= link_to "Cancel", orders_path, class: "btn btn-info" %>
        
         <div class="hidden">
                <%= f.input :total_price %>
                <%= f.simple_fields_for :order_lines do |order_line| %>
                    <%= render 'order_line_fields', f: order_line %>
                <% end %>
             </div>
    <% end %>
</p>

</div>
</div>