config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index', to: 'welcome#index', as: :welcome_index

  devise_for :cashiers, path: 'cashiers'
  
  devise_for :admins, path: 'admins'
  
  resources :products
  get '/report', to: 'products#report', as: :products_reports
  
  
  resources :cashiers, except: :create
  post 'create_cashier' => 'cashiers#create', as: :create_cashier
  
  resources :orders
  post 'orders/summary', to: 'orders#summary', as: :orders_summary
  get 'cashierreport/:id', to: 'orders#cashierreport', as: :cashierreport
  get 'orders/:id/refund/', to: 'orders#refund', as: :orders_refund
  post 'orders/:id', to: 'orders#update', as: :update_order
  
  resources :cashiers_admin, :controller => 'cashiers'
  

  root :to => 'welcome#index'
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :admin
  has_many :orders
  
  def active_for_authentication?
    super and self.status?
  end
  
end

app/controllers/cashiers/confirmations_controller.rb
class Cashiers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/cashiers/omniauth_callbacks_controller.rb
class Cashiers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/cashiers/passwords_controller.rb
class Cashiers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/cashiers/registrations_controller.rb
class Cashiers::RegistrationsController < Devise::RegistrationsController
  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/cashiers/sessions_controller.rb
class Cashiers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  #def new
  #    super
  #end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/cashiers/unlocks_controller.rb
class Cashiers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_cashier, only: [:destroy]
    def destroy
        if @cashier.status == true
            @cashier.status = false
        else
            @cashier.status = true
        end
        if @cashier.save
            redirect_to cashiers_path
        end
    end
    
    def create
        @cashier = Cashier.new(cashier_params)
        @cashier.status = true
        @cashier.admin = current_admin
        @cashier.save
        @cashier_registration = @cashier
        redirect_to @cashier
    end
  
    def new
        @cashier = Cashier.new
    end
    
    def index
        #@cashiers = Cashier.where(status:true)
        @cashiers = Cashier.all
    end
    
    def edit
        @cashier = Cashier.find(params[:id])
        if @cashier.admin != current_admin
            redirect_to cashiers_path
        end
        
    end
    
    def view
        id = params[:id]
        @cashier = Cashier.find(id)
    end
    
    def show
        id = params[:id]
        @cashier = Cashier.find(id)
    end
    
    def update
        @cashier = Cashier.find(params[:id])
        @cashier.update(cashier_params)
        @cashier.save
        redirect_to @cashier
    end
    
    def deactivate
        @cashier = Product.find(params[:id])
        @cashier.status = false
        @cashier.save
        redirect_to cashiers_path
    end
    
    def activate
        @cashier = Product.find(params[:id])
        @cashier.status = true
         @cashier.save
        redirect_to cashiers_path
    end

    private
        def cashier_params
            params.require(:cashier).permit(:email, :password, :password_confirmation, :name, :status)
        end
        def set_cashier
            @cashier = Cashier.find_by(id: params[:id])
            redirect_to cashiers_path, notice: "Cashier not found." if @cashier.nil?
        end
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/views/cashiers/_cashierform.html.erb
<br>
<div class="col-4 col-sm-7">

<%= simple_form_for Cashier.new, url: create_cashier_path  do |f| %> 
  
      <p class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </p>
      <p class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </p>
      <p class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </p>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name, size: 40 %>
      </p>
 <br>
    <p>
      <%= f.submit "Create Cashier Account", class:"btn btn-info" %>
      <br>
       <br>
      <%= link_to "Cancel", cashiers_admin_index_path, class: 'button' %>
    </p>
<% end %>

</div>

app/views/cashiers/edit.html.erb
<fieldset>
<br>

<div class="col-4 col-sm-7">
<h2>Edit Cashier</h2>
<%= simple_form_for @cashier, url: cashiers_admin_path(@cashier)  do |f| %> 
      <p class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </p>
      <p class="required">
        <%= f.label :password, "New Password" %>
        <%= f.password_field :password, size: 40 %>
      </p>
      <p class="required">
        <%= f.label :password_confirmation, "Confirm New Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </p>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name, size: 40 %>
      </p>

      <p>
          <%= f.check_box :status %> Active
      </p>

    </ol>
    <p>
      <% if @cashier.new_record? %>
        <%= f.submit "Create Cashier Account" %>
      <% else %>
        <%= f.submit "Update Account" %>
      <% end %>
      <br>
      <br>
      <%= link_to "Cancel", cashiers_admin_index_path, class: 'button' %>
    </p>
<% end %>
</div>
</fieldset>

app/views/cashiers/index.html.erb
<div class="card">
  <div class="card-block">
<br>
<h2>Cashiers</h2>
<br>
<p><%= link_to "New Cashier", '/cashiers/new',  class: "btn btn-primary" %></p>
<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Status</th>
        <th>Admin Email</th>
        <th> </th>
        <th> </th>
        <th> </th>
    </tr>
    <% @cashiers.each do |p| %>
        <tr>
            <td><%= p.name %></td>
            <td><%= p.email %></td>
            <td><%= if p.status==true then "Activated" else "Deactivated" end %></td>
            <td><%= p.admin.email %></td>
            <td><%= link_to "Show", cashier_path(p),  class: "btn btn-primary" %></td>
            
            <td><%= link_to "Edit", edit_cashier_path(p),  class: "btn btn-primary" %></td>
            <td>
                <% if p.status==true %>
                    <%= link_to "Deactivate", p, method: :delete, class: "btn btn-danger" %>
                <% else %>
                    <%= link_to "Activate", p, method: :delete, class: "btn btn-info" %>
                <% end %>
            </td>
        </tr>
    <% end %>
</table> 
</div>
</div>

app/views/cashiers/new.html.erb
<fieldset>

<h2>New Cashier</h2>
<br>
<%= render 'cashierform' %> 

</fieldset>

app/views/cashiers/show.html.erb
<fieldset>
  <div class="card-block">
<br>

<h2>Show Cashier</h2>
<h3> Cashier #<%= @cashier.id %></h3><br>

<h4><%= @cashier.name %></h4>
<h4><%= @cashier.email%></h4>

<p>
    <%= if @cashier.status then "Status: Active" else "Status: Inactive" end %>
</p>
<%= link_to "Back to Index", cashiers_path %><br>
<%= link_to "Edit", edit_cashier_path(@cashier) %>

</div>
</fieldset>