config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index', to: 'welcome#index', as: :welcome_index

  devise_for :cashiers, path: 'cashiers'
  
  devise_for :admins, path: 'admins'
  
  resources :products
  get '/report', to: 'products#report', as: :products_reports
  
  
  resources :cashiers, except: :create
  post 'create_cashier' => 'cashiers#create', as: :create_cashier
  
  resources :orders
  post 'orders/summary', to: 'orders#summary', as: :orders_summary
  get 'cashierreport/:id', to: 'orders#cashierreport', as: :cashierreport
  get 'orders/:id/refund/', to: 'orders#refund', as: :orders_refund
  post 'orders/:id', to: 'orders#update', as: :update_order
  
  resources :cashiers_admin, :controller => 'cashiers'
  

  root :to => 'welcome#index'
end

app/views/layouts/_nav.html.erb
<nav id ="nav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid navbar-fnt">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <a class="navbar-brand" href="/welcome/index">
    <img src="http://i.imgur.com/5pwcyoW.png" style="height: 100px;"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <% if admin_signed_in? %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/products/">Products</a></li>
        <li><a href="/cashiers">Cashiers</a></li>
        <li><a href="/report/">Report</a></li>
      </ul>
    <% elsif cashier_signed_in? %>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/orders/">Orders</a></li>
      </ul>
    <% else %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <%end%> 
      
    <p class="navbar-text pull-right">
        <% if admin_signed_in? %>
          Logged in as <strong><%= current_admin.email %></strong>
          <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "navbar-link"%>
        <% elsif cashier_signed_in? %>
          Logged in as <strong><%= current_cashier.email %></strong>
          <%= link_to "Logout", destroy_cashier_session_path, method: :delete, class: "navbar-link"%>
          <% end %>
      </p> 

      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<h2>Welcome</h2>

app/views/layouts/splash.html.erb
<center>
    <div>
        <h1>Are you Admin or Cashier?</h1>
    </div>
    <div>
        <a href=/cashiers/sign_in>Cashier</a>
        <a href=/admin/sign_in>Admin</a>
    </div>
</center>